services:
  # Container definition for the devcontainer
  devcontainer:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10.16}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/zapman/

networks:
  default:
    name: zapman-network
